"""
state.py
Sandbox state for the Charts sheet: the once-per-Open restore, the
pre-Save capture into settings["charts_sheet_state"], and the three
clears -- a full Reset, and the two narrower ones that drop only the keys
referencing a specific Running Order row or Chart Store entry.
"""

import json

import streamlit as st

from chartgen.shared.infrastructure.page_sizing import STANDARD_PAGE_SIZES_EMU
from chartgen.ui.tabs.charts_tab.constants import (
    CHART_STORE_PLACEHOLDER, CHART_STORE_REFERENCING_KEYS, CHART_STORE_TARGET_PLACEHOLDER,
    CS_KEY_PREFIX, RO_PLACEHOLDER, ROW_REFERENCING_KEYS, TARGET_PLACEHOLDER,
)


def _clear_sandbox_state():
    # "cs_tab_rendered" is deliberately preserved — deleting it would make
    # the next render treat the sheet as freshly opened, which would
    # re-trigger _restore_charts_sheet_state and silently reload whatever
    # was last saved to settings["charts_sheet_state"] instead of actually
    # giving Reset a blank sandbox. Mirrors output_tables_tab/state.py's own
    # Reset, which already guards against exactly this.
    keep = {"cs_tab_rendered"}
    for k in list(st.session_state.keys()):
        if k.startswith(CS_KEY_PREFIX) and k not in keep:
            del st.session_state[k]


def _clear_row_referencing_state():
    for k in ROW_REFERENCING_KEYS:
        st.session_state.pop(k, None)


def _clear_chart_store_referencing_state():
    for k in CHART_STORE_REFERENCING_KEYS:
        st.session_state.pop(k, None)


# Charts sheet fields persisted across Save and reopen. Distinct from
# CHART_SANDBOX_FIELDS: that is what gets written back to a Running Order
# row on an explicit Save, this is a snapshot of the sandbox's own control
# values whether or not they were ever saved to a row.
#
# Zoom is excluded, being screen-only. An in-progress Custom Charts
# paste-back is excluded too: it is unvalidated code.


def _restore_charts_sheet_state(the_settings, row_id_to_idx, the_manifest, label_by_cache_file, chart_store_by_id):
    """
    Re-stage the Charts sheet's widget state from settings["charts_sheet_state"]
    (written by capture_charts_sheet_state at Save), so the sheet looks the
    same as when it was last saved. Called once per workfile Open. Every
    field is defensively re-validated against what's actually available
    right now (rows, cache files, page sizes) rather than trusted blindly —
    a Running Order regenerated by a template re-upload, or a chart deleted
    since, should fall back cleanly rather than error.
    """
    raw = (the_settings or {}).get("charts_sheet_state", "")
    if not raw:
        return
    try:
        state = json.loads(raw)
    except (TypeError, ValueError):
        return

    cache_file = state.get("cache_file", "")
    if cache_file in label_by_cache_file:
        st.session_state["cs_shape_choice"] = label_by_cache_file[cache_file]
        st.session_state["cs_last_shape_choice"] = label_by_cache_file[cache_file]
        st.session_state["cs_selected_cache_file"] = cache_file

    ro_row_id = state.get("ro_row_id")
    if ro_row_id in row_id_to_idx:
        st.session_state["cs_ro_choice"] = ro_row_id
        st.session_state["cs_last_loaded_ro"] = ro_row_id
        st.session_state["cs_bound_row_idx"] = row_id_to_idx[ro_row_id]
        st.session_state["cs_bound_shape_type"] = the_manifest.get(cache_file, {}).get("shape_type", "")
    else:
        st.session_state["cs_ro_choice"] = RO_PLACEHOLDER
        st.session_state["cs_last_loaded_ro"] = RO_PLACEHOLDER

    chart_store_id = state.get("chart_store_id")
    if chart_store_id in chart_store_by_id:
        st.session_state["cs_chart_store_choice"] = chart_store_id
        st.session_state["cs_last_loaded_chart_store"] = chart_store_id
        st.session_state["cs_bound_chart_store_id"] = chart_store_id
    else:
        st.session_state["cs_chart_store_choice"] = CHART_STORE_PLACEHOLDER
        st.session_state["cs_last_loaded_chart_store"] = CHART_STORE_PLACEHOLDER

    st.session_state["cs_base_chart_name"] = state.get("base_chart_name", "")
    st.session_state["cs_populations_tokens"] = list(state.get("populations_tokens", []))
    st.session_state["cs_start_period"] = state.get("start_period", "")
    st.session_state["cs_end_period"] = state.get("end_period", "")
    st.session_state["cs_metric_periods"] = list(state.get("metric_periods", []))
    st.session_state["cs_tweaks_str"] = state.get("tweaks", "")

    # A persisted value is shown exactly as stored, however small or large.
    # The Sizing box is a save-back surface, so any number substituted here
    # gets committed to the row on the next save. A value that will not
    # parse at all is reported rather than replaced silently; the key is
    # left unset and the setdefault further down supplies the starting
    # value, with the user told why.
    for key, label in (("width_pct", "Width"), ("height_pct", "Height")):
        raw = state.get(key, 50.0)
        try:
            st.session_state["cs_" + key] = float(raw)
        except (TypeError, ValueError):
            st.error(
                f"Stored Charts sheet {label.lower()} ({raw!r}) is not a number, so it could not "
                f"be restored. The box below shows a starting value, not your stored one. Use "
                f"Reset to clear the saved Charts sheet configuration."
            )

    manual_page_size = state.get("manual_page_size")
    if manual_page_size in STANDARD_PAGE_SIZES_EMU:
        st.session_state["cs_manual_page_size"] = manual_page_size

    action = state.get("action", "Overwrite selected row")
    if action in ("Overwrite selected row", "Insert above selected row", "Insert below selected row"):
        st.session_state["cs_action"] = action

    target_row_id = state.get("target_row_id")
    if target_row_id in row_id_to_idx:
        st.session_state["cs_target_row_choice"] = target_row_id

    chart_store_action = state.get("chart_store_action", "Add new entry")
    if chart_store_action in ("Add new entry", "Overwrite selected entry"):
        st.session_state["cs_chart_store_action"] = chart_store_action

    chart_store_target_id = state.get("chart_store_target_id")
    if chart_store_target_id in chart_store_by_id:
        st.session_state["cs_chart_store_target_choice"] = chart_store_target_id

    st.session_state["cs_chart_store_description"] = state.get("chart_store_description", "")


def capture_charts_sheet_state(workfile_state):
    """
    Snapshot the Charts sheet's current control values into
    settings["charts_sheet_state"] (JSON), called just before Save/Save As/
    Save and Close (sidebar.py, save_as_form.py) so a reopen can restore
    them via _restore_charts_sheet_state. Only overwrites if the Charts tab
    has actually been rendered this session ("cs_tab_rendered") — otherwise
    the sandbox holds nothing meaningful to capture, and whatever was
    captured last time should be left as-is.
    """
    if "cs_tab_rendered" not in st.session_state:
        return

    ro_choice = st.session_state.get("cs_ro_choice", RO_PLACEHOLDER)
    target_choice = st.session_state.get("cs_target_row_choice", TARGET_PLACEHOLDER)
    chart_store_choice = st.session_state.get("cs_chart_store_choice", CHART_STORE_PLACEHOLDER)
    chart_store_target_choice = st.session_state.get("cs_chart_store_target_choice", CHART_STORE_TARGET_PLACEHOLDER)

    state = {
        "ro_row_id": ro_choice if ro_choice != RO_PLACEHOLDER else None,
        "cache_file": st.session_state.get("cs_selected_cache_file", ""),
        "base_chart_name": st.session_state.get("cs_base_chart_name", ""),
        "populations_tokens": st.session_state.get("cs_populations_tokens", []),
        "start_period": st.session_state.get("cs_start_period", ""),
        "end_period": st.session_state.get("cs_end_period", ""),
        "metric_periods": st.session_state.get("cs_metric_periods", []),
        "tweaks": st.session_state.get("cs_tweaks_str", ""),
        "width_pct": st.session_state.get("cs_width_pct", 50.0),
        "height_pct": st.session_state.get("cs_height_pct", 50.0),
        "manual_page_size": st.session_state.get("cs_manual_page_size"),
        "action": st.session_state.get("cs_action", "Overwrite selected row"),
        "target_row_id": target_choice if target_choice != TARGET_PLACEHOLDER else None,
        "chart_store_id": chart_store_choice if chart_store_choice != CHART_STORE_PLACEHOLDER else None,
        "chart_store_action": st.session_state.get("cs_chart_store_action", "Add new entry"),
        "chart_store_target_id": (
            chart_store_target_choice if chart_store_target_choice != CHART_STORE_TARGET_PLACEHOLDER else None
        ),
        "chart_store_description": st.session_state.get("cs_chart_store_description", ""),
    }
    workfile_state.settings["charts_sheet_state"] = json.dumps(state)
